"""eToro XLSX parser — robusto contro variazioni di formato.

Il file Account Statement di eToro (XLSX) contiene tipicamente piu' fogli:
  - "Account Summary"      — saldi e P&L totali
  - "Closed Positions"     — posizioni chiuse
  - "Account Activity"     — log transazioni (depositi, prelievi, fee, dividendi)
  - "Open Positions"       (o "Positions")  — posizioni aperte CORRENTI

I nomi colonne possono variare tra release del file. Il parser usa una
strategia di matching tollerante:
  - Trova il foglio "Open Positions" (case insensitive, fuzzy match).
  - Per ogni colonna richiesta, cerca tra alias noti (es. "Action" oppure
    "Stock"/"Symbol"/"Asset" per il ticker).
  - Restituisce un DataFrame normalizzato con colonne fisse.

Formato di output normalizzato:
  ticker, direction, quantity, open_price, current_price, open_date,
  market_value, profit_pct, profit_eur, currency, raw_action

Nessuna colonna obbligatoria solleva eccezioni: eventuali campi mancanti
restano NaN, e ImportReviewWorkflow li flagga come WARN per la review utente.

Bugfix v7.1.1:
  - _reposition_header: ora rileva correttamente le colonne "Unnamed: N"
    auto-assegnate da pandas quando l'XLSX ha righe decorative in cima.
  - _normalize_direction: signature corretta (-> str | None) per coerenza
    con i tipi reali ritornati. mypy --strict ora accetta.
"""
from __future__ import annotations

import re
import unicodedata
from io import BytesIO
from typing import Any, BinaryIO

import pandas as pd

__version__ = "7.1.1"

__all__ = ["EToroParser", "EToroParseError", "EToroPosition"]


class EToroParseError(Exception):
    """Sollevata quando il file XLSX non sembra un export eToro valido."""


# ──────────────────────────────────────────────────────────── alias colonne
# Mappa: nome_normalizzato -> lista di pattern noti (regex case-insensitive)
# Ordine: piu' specifico -> piu' generico.
_COLUMN_ALIASES: dict[str, list[str]] = {
    "raw_action": [
        # Bugfix v7.1.1: rimosso "^action$" da raw_action perche' nei report
        # eToro recenti "Action" indica Buy/Sell (direction), non il nome
        # dello strumento. Per il nome strumento restano gli alias
        # piu' specifici.
        r"^stock$",
        r"^asset.*name$",
        r"^instrument$",
        r"^name$",
    ],
    "ticker": [
        r"^symbol$",
        r"^ticker$",
        r"^asset.*symbol$",
        r"^isin$",
    ],
    "direction": [
        r"^type$",         # eToro: "Buy"/"Sell"
        r"^action$",       # eToro recenti: "Action" = Buy/Sell
        r"^direction$",
        r"^side$",
        r"^buy.?sell$",
    ],
    "quantity": [
        r"^units$",       # eToro
        r"^amount$",
        r"^quantity$",
        r"^qty$",
        r"^size$",
    ],
    "open_price": [
        r"^open.*rate$",
        r"^open.*price$",
        r"^entry.*price$",
        r"^buy.*price$",
        r"^avg.*price$",
        r"^cost.*price$",
        r"^price.*open$",
    ],
    "current_price": [
        r"^current.*rate$",
        r"^current.*price$",
        r"^market.*price$",
        r"^last.*price$",
        r"^rate$",
        r"^price$",
    ],
    "open_date": [
        r"^open.*date$",
        r"^entry.*date$",
        r"^date.*open$",
        r"^purchase.*date$",
        r"^opened$",
    ],
    "market_value": [
        r"^value$",
        r"^market.*value$",
        r"^position.*value$",
        r"^current.*value$",
        r"^equity$",
    ],
    "profit_pct": [
        r"^profit.*\(?%\)?$",
        r"^p.?l.*\(?%\)?$",
        r"^pnl.*\(?%\)?$",
        r"^return.*%$",
    ],
    "profit_eur": [
        r"^profit$",
        r"^p.?l$",
        r"^pnl$",
        r"^profit.*\(?eur\)?$",
        r"^profit.*\(?usd\)?$",
        r"^profit.*\(?\$\)?$",
        r"^realized.*p.?l$",
        r"^unrealized.*p.?l$",
    ],
    "currency": [
        r"^currency$",
        r"^ccy$",
    ],
}

# Pattern dei nomi foglio per le posizioni aperte
_SHEET_PATTERNS_OPEN = [
    re.compile(r"^open.?positions?$", re.IGNORECASE),
    re.compile(r"^positions?$", re.IGNORECASE),
    re.compile(r"^holdings?$", re.IGNORECASE),
    re.compile(r"^current.?positions?$", re.IGNORECASE),
]

# Pattern delle colonne "fasulle" che pandas auto-assegna quando un XLSX
# ha celle decorative o vuote in cima:
#   - "Unnamed: 1", "Unnamed: 2", ...  (formato pandas standard)
#   - 0, 1, 2 (RangeIndex puro, se header=None viene applicato)
_PANDAS_AUTO_HEADER_RE = re.compile(r"^unnamed:\s*\d+$", re.IGNORECASE)


def _is_pandas_autogenerated_header(col: Any) -> bool:
    """True se il nome colonna sembra auto-generato da pandas.

    Pandas assegna "Unnamed: N" quando legge un foglio Excel con celle
    vuote o non-string nella prima riga. In quel caso l'header reale
    e' sotto, e _reposition_header() deve trovarlo.
    """
    if col is None:
        return True
    if isinstance(col, str):
        return bool(_PANDAS_AUTO_HEADER_RE.match(col.strip()))
    # Numerico (int/float) -> RangeIndex (header=None style)
    if isinstance(col, (int, float)):
        return True
    return False


class EToroPosition(dict[str, Any]):
    """Posizione eToro normalizzata (dict per facilita' editor Streamlit)."""


class EToroParser:
    """Parser robusto per Account Statement eToro.

    Esempio d'uso::

        parser = EToroParser()
        df = parser.parse(uploaded_xlsx_file)
        # df ha colonne: ticker, direction, quantity, open_price, ...
    """

    def parse(self, source: str | BinaryIO | bytes) -> pd.DataFrame:
        """Legge il foglio Open Positions e ritorna un DataFrame normalizzato.

        Args:
            source: Path al file, file-like object, o bytes.

        Returns:
            DataFrame con colonne normalizzate. Le righe vuote sono rimosse.

        Raises:
            EToroParseError: se il file non contiene un foglio riconoscibile
                come "Open Positions".
        """
        # 1. Carica il workbook con tutti i fogli
        try:
            if isinstance(source, bytes):
                source = BytesIO(source)
            sheets = pd.read_excel(source, sheet_name=None, engine="openpyxl")
        except ImportError as exc:
            # pandas tenta import_optional_dependency("openpyxl") al momento
            # della lettura: se mancante, qui arriva un ImportError. Tradurlo
            # in errore chiaro per l'utente con istruzioni di installazione.
            raise EToroParseError(
                "La libreria 'openpyxl' non è installata. "
                "È necessaria per leggere file Excel (.xlsx). "
                "Installa con: poetry add openpyxl  (oppure: pip install openpyxl)"
            ) from exc
        except (ValueError, OSError, KeyError) as exc:
            raise EToroParseError(
                f"Impossibile leggere il file XLSX: {exc}. "
                f"Verifica che sia un file Excel valido."
            ) from exc

        if not sheets:
            raise EToroParseError("Il file XLSX non contiene alcun foglio.")

        # 2. Trova il foglio Open Positions
        open_sheet_name = self._find_open_positions_sheet(sheets)
        if open_sheet_name is None:
            available = ", ".join(sheets.keys())
            raise EToroParseError(
                f"Foglio 'Open Positions' non trovato. "
                f"Fogli disponibili: {available}. "
                f"Esporta da eToro con 'Account Statement' completo."
            )

        df = sheets[open_sheet_name]

        # 3. Alcuni export eToro hanno righe-titolo prima del header reale.
        df = self._reposition_header(df)

        # 4. Normalizza colonne via alias matching
        df = self._normalize_columns(df)

        # 5. Rimuovi righe completamente vuote
        df = df.dropna(how="all")
        if df.empty:
            raise EToroParseError(
                f"Foglio '{open_sheet_name}' vuoto. "
                f"Non ci sono posizioni aperte da importare."
            )

        # 6. Pulisci e tipizza valori
        df = self._coerce_types(df)

        # 7. Reset index (utile per ImportReviewWorkflow)
        df = df.reset_index(drop=True)

        return df

    # ─────────────────────────────────────────────────────── helpers
    @staticmethod
    def _find_open_positions_sheet(
        sheets: dict[str, pd.DataFrame],
    ) -> str | None:
        """Trova il nome del foglio Open Positions tramite fuzzy matching."""
        for pattern in _SHEET_PATTERNS_OPEN:
            for sheet_name in sheets:
                if pattern.search(sheet_name.strip()):
                    return sheet_name
        # Fallback: foglio piu' lungo che ha colonne riconoscibili
        best_name: str | None = None
        best_score = 0
        for sheet_name, df in sheets.items():
            if df is None or df.empty:
                continue
            cols_norm = [_normalize_text(str(c)) for c in df.columns]
            score = sum(
                1
                for canonical_aliases in _COLUMN_ALIASES.values()
                for pattern in canonical_aliases
                if any(re.match(pattern, c) for c in cols_norm)
            )
            if score > best_score:
                best_score = score
                best_name = sheet_name
        # Soglia minima: almeno 3 colonne note rilevate
        return best_name if best_score >= 3 else None

    @staticmethod
    def _reposition_header(df: pd.DataFrame) -> pd.DataFrame:
        """Se la prima riga sembra un titolo e non header, riposiziona.

        Alcuni export eToro hanno celle decorative prime delle 1-3 righe
        (es. "Account Statement", date di esportazione, righe vuote).
        In quel caso pandas assegna alle colonne "Unnamed: 0", "Unnamed: 1"...
        e l'header REALE si trova nelle prime righe del dataframe.

        Bugfix v7.1.1: il check precedente
            ``all(isinstance(c, str) and c.strip() ...)``
        passava anche per "Unnamed: 1", "Unnamed: 2" (sono stringhe non
        vuote!) e quindi usciva senza riposizionare. Risultato: tutte le
        colonne normalizzate diventavano NaN. Ora il check usa
        ``_is_pandas_autogenerated_header()`` che riconosce il pattern.
        """
        if df.empty:
            return df

        # Se TUTTE le colonne sono nomi reali (non "Unnamed: N", non numeri),
        # il header e' gia' al posto giusto.
        if not any(_is_pandas_autogenerated_header(c) for c in df.columns):
            return df

        # Cerca una riga "header reale" nelle prime 5 righe.
        # Una riga e' un header reale se almeno una sua cella matcha un
        # alias noto (Symbol, Action, Type, Units, ...).
        all_aliases = []
        for canonical_aliases in _COLUMN_ALIASES.values():
            all_aliases.extend(canonical_aliases)

        for i in range(min(5, len(df))):
            row = df.iloc[i]
            row_strs = [
                _normalize_text(str(v)) for v in row.values if pd.notna(v)
            ]
            if not row_strs:
                continue
            # Conta quanti match ci sono in questa riga
            n_matches = sum(
                1
                for cell_str in row_strs
                for pattern in all_aliases
                if re.match(pattern, cell_str)
            )
            # Soglia minima: almeno 2 colonne riconosciute = e' una riga header
            if n_matches >= 2:
                # Riposiziona: usa questa riga come header e scarta quelle
                # precedenti (decorative).
                new_columns = list(row.values)
                df_repositioned = df.iloc[i + 1:].reset_index(drop=True)
                df_repositioned.columns = new_columns
                return df_repositioned

        # Nessun header riconoscibile trovato: ritorna df invariato e lascia
        # che _normalize_columns faccia del suo meglio (risultera' in molti NaN
        # che ImportReviewWorkflow flaggherà come review-required).
        return df

    @staticmethod
    def _normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
        """Mappa le colonne XLSX -> nomi canonici del nostro schema.

        Strategia: per ogni nome canonico, prova ogni alias regex contro
        le colonne normalizzate del DataFrame; appena trova un match, mappa.
        """
        normalized_cols = {
            col: _normalize_text(str(col)) for col in df.columns
        }
        canonical_to_actual: dict[str, Any] = {}
        used_actual: set[Any] = set()
        for canonical, patterns in _COLUMN_ALIASES.items():
            for pattern in patterns:
                for actual_col, norm in normalized_cols.items():
                    if actual_col in used_actual:
                        continue
                    if re.match(pattern, norm):
                        canonical_to_actual[canonical] = actual_col
                        used_actual.add(actual_col)
                        break
                if canonical in canonical_to_actual:
                    break

        # Costruisci nuovo DataFrame con colonne normalizzate
        out = pd.DataFrame()
        for canonical in _COLUMN_ALIASES:
            actual = canonical_to_actual.get(canonical)
            if actual is not None:
                out[canonical] = df[actual].values
            else:
                # Colonna mancante: NaN, sara' flagged in review
                out[canonical] = pd.NA

        # Aggiungi colonne extra non riconosciute come '_extra_<nome>'
        for actual_col in df.columns:
            if actual_col in used_actual:
                continue
            # Salta le colonne pandas-autogenerate (di solito tutte vuote
            # se siamo arrivati qui senza riposizionamento)
            if _is_pandas_autogenerated_header(actual_col):
                continue
            out[f"_extra_{actual_col}"] = df[actual_col].values

        return out

    @staticmethod
    def _coerce_types(df: pd.DataFrame) -> pd.DataFrame:
        """Conversione tipi: numerici a float, date a Timestamp, stringhe pulite."""
        df = df.copy()

        # Numerici
        numeric_cols = [
            "quantity",
            "open_price",
            "current_price",
            "market_value",
            "profit_pct",
            "profit_eur",
        ]
        for col in numeric_cols:
            if col in df.columns:
                df[col] = pd.to_numeric(
                    df[col].astype(str).str.replace(",", "."),
                    errors="coerce",
                )

        # Date
        if "open_date" in df.columns:
            df["open_date"] = pd.to_datetime(df["open_date"], errors="coerce")

        # Direction: normalizza in {LONG, SHORT}. Restituisce stringa o None;
        # convertiamo None in pd.NA per coerenza pandas dopo l'apply.
        if "direction" in df.columns:
            df["direction"] = (
                df["direction"].apply(_normalize_direction).astype("string")
            )

        # Ticker: uppercase
        if "ticker" in df.columns:
            df["ticker"] = (
                df["ticker"]
                .astype(str)
                .str.strip()
                .str.upper()
                .replace({"NAN": pd.NA, "<NA>": pd.NA, "NONE": pd.NA})
            )

        # Currency: uppercase
        if "currency" in df.columns:
            df["currency"] = (
                df["currency"]
                .astype(str)
                .str.strip()
                .str.upper()
                .replace({"NAN": pd.NA, "<NA>": pd.NA, "NONE": pd.NA})
            )

        return df


def _normalize_text(s: str) -> str:
    """Normalizzazione case-insensitive senza spazi/accenti per matching."""
    s = s.strip().lower()
    # Rimuove accenti
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if not unicodedata.combining(c))
    # Collassa spazi multipli e simboli in singolo spazio
    s = re.sub(r"\s+", " ", s)
    return s


def _normalize_direction(value: Any) -> str | None:
    """Mappa Buy/Sell/Long/Short -> LONG/SHORT.

    Bugfix v7.1.1: signature dichiarata correttamente come ``str | None``
    (non ``str | float``). I valori non riconosciuti ritornano ``None`` e
    sono successivamente convertiti in ``pd.NA`` da ``astype('string')``
    nel chiamante. Questo soddisfa mypy --strict.
    """
    if pd.isna(value):
        return None
    s = str(value).strip().lower()
    if s in {"buy", "long", "l"}:
        return "LONG"
    if s in {"sell", "short", "s"}:
        return "SHORT"
    return None
