"""Test del bugfix v7.1.1 sul parser eToro.

Verifica:
  1. _is_pandas_autogenerated_header() riconosce "Unnamed: N" e numerici.
  2. _reposition_header() trova l'header reale anche con "Unnamed:" cols.
  3. _normalize_direction() ha signature corretta (str | None) e ritorna
     None invece di pd.NA per permettere mypy --strict.
"""
from __future__ import annotations

from io import BytesIO

import pandas as pd
import pytest
from openpyxl import Workbook

from personal.data_entry.etoro_parser import (
    EToroParser,
    _is_pandas_autogenerated_header,
    _normalize_direction,
)


# ============================================ _is_pandas_autogenerated_header
def test_unnamed_header_recognized() -> None:
    """'Unnamed: 1', 'Unnamed: 2'... sono auto-generated da pandas."""
    assert _is_pandas_autogenerated_header("Unnamed: 0") is True
    assert _is_pandas_autogenerated_header("Unnamed: 1") is True
    assert _is_pandas_autogenerated_header("Unnamed: 99") is True
    assert _is_pandas_autogenerated_header("unnamed: 1") is True  # case insensitive


def test_real_header_not_recognized_as_auto() -> None:
    """Header reali come 'Symbol', 'Action' NON sono auto-generated."""
    assert _is_pandas_autogenerated_header("Symbol") is False
    assert _is_pandas_autogenerated_header("Action") is False
    assert _is_pandas_autogenerated_header("Open Rate") is False


def test_numeric_header_recognized_as_auto() -> None:
    """Numerici (RangeIndex) sono auto-generated."""
    assert _is_pandas_autogenerated_header(0) is True
    assert _is_pandas_autogenerated_header(1) is True
    assert _is_pandas_autogenerated_header(42.0) is True


def test_none_header_recognized_as_auto() -> None:
    """None e' auto-generated."""
    assert _is_pandas_autogenerated_header(None) is True


# ===================================================== _normalize_direction
def test_normalize_direction_buy() -> None:
    """Buy/long/L -> 'LONG'."""
    assert _normalize_direction("Buy") == "LONG"
    assert _normalize_direction("BUY") == "LONG"
    assert _normalize_direction("long") == "LONG"
    assert _normalize_direction("L") == "LONG"


def test_normalize_direction_sell() -> None:
    """Sell/short/S -> 'SHORT'."""
    assert _normalize_direction("Sell") == "SHORT"
    assert _normalize_direction("short") == "SHORT"
    assert _normalize_direction("S") == "SHORT"


def test_normalize_direction_unknown_returns_none() -> None:
    """Bugfix v7.1.1: ritorna None (non pd.NA), coerente con signature."""
    result = _normalize_direction("xyz")
    assert result is None
    # Type check semantico: None e' compatibile con 'str | None'
    assert isinstance(result, type(None))


def test_normalize_direction_nan_returns_none() -> None:
    """NaN ritorna None."""
    assert _normalize_direction(float("nan")) is None
    assert _normalize_direction(pd.NA) is None
    assert _normalize_direction(None) is None


# ====================================== _reposition_header (CRITICAL FIX)
def test_reposition_header_with_unnamed_cols() -> None:
    """Test critico: XLSX con 2 righe decorative in cima.

    Pandas legge il foglio e assegna 'Unnamed: 0', 'Unnamed: 1' alle colonne.
    L'header REALE e' nella riga 1 del DataFrame (riga 2 dell'XLSX).
    Bugfix v7.1.1: prima il check
        all(isinstance(c, str) and c.strip() ...)
    passava perche' "Unnamed: 0" e' una stringa non vuota -> usciva senza
    riposizionare. Ora _is_pandas_autogenerated_header() lo riconosce.
    """
    # Simula DataFrame con header pandas-autogenerato
    df = pd.DataFrame(
        {
            "Unnamed: 0": ["Account Statement", None, "Symbol", "AAPL", "MSFT"],
            "Unnamed: 1": ["2025-01-01", None, "Action", "Buy", "Sell"],
            "Unnamed: 2": [None, None, "Units", 10, 5],
            "Unnamed: 3": [None, None, "Open Rate", 187.42, 420.0],
        }
    )
    repositioned = EToroParser._reposition_header(df)

    # Il nuovo header deve essere quello che era sulla riga 2 del df originale
    assert "Symbol" in list(repositioned.columns)
    assert "Action" in list(repositioned.columns)
    assert "Units" in list(repositioned.columns)
    # I dati restanti devono essere AAPL/Buy/10 e MSFT/Sell/5
    assert len(repositioned) == 2
    # Almeno 1 cella deve contenere AAPL
    assert (repositioned == "AAPL").any().any()


def test_reposition_header_already_clean_passthrough() -> None:
    """Se il df ha gia' header reali, _reposition_header non fa nulla."""
    df = pd.DataFrame(
        {
            "Symbol": ["AAPL", "MSFT"],
            "Action": ["Buy", "Sell"],
            "Units": [10, 5],
        }
    )
    repositioned = EToroParser._reposition_header(df)
    assert list(repositioned.columns) == ["Symbol", "Action", "Units"]
    assert len(repositioned) == 2


def test_reposition_header_no_match_returns_original() -> None:
    """Se nessuna riga sembra un header reale, ritorna df invariato."""
    df = pd.DataFrame(
        {
            "Unnamed: 0": ["foo", "bar", "baz"],
            "Unnamed: 1": [1, 2, 3],
        }
    )
    repositioned = EToroParser._reposition_header(df)
    # Stesse colonne (non riposizionate)
    assert list(repositioned.columns) == ["Unnamed: 0", "Unnamed: 1"]


# ========================================== integration: parse XLSX reale
def _make_xlsx_with_decorative_rows() -> bytes:
    """Costruisce un XLSX di test con 2 righe decorative + header reale."""
    wb = Workbook()
    ws = wb.active
    ws.title = "Open Positions"
    # Riga 1: titolo decorativo
    ws.append(["eToro Account Statement"])
    # Riga 2: vuota
    ws.append([])
    # Riga 3: header reale
    ws.append(["Symbol", "Action", "Units", "Open Rate", "Open Date"])
    # Righe 4+: data
    ws.append(["AAPL", "Buy", 10, 187.42, "2024-06-01"])
    ws.append(["MSFT", "Sell", 5, 420.0, "2024-08-15"])
    out = BytesIO()
    wb.save(out)
    out.seek(0)
    return out.getvalue()


def test_parse_xlsx_with_decorative_rows() -> None:
    """End-to-end: parse XLSX con righe decorative -> ticker AAPL/MSFT
    devono essere correttamente normalizzati nel DataFrame finale."""
    xlsx_bytes = _make_xlsx_with_decorative_rows()
    parser = EToroParser()
    df = parser.parse(xlsx_bytes)

    # 2 posizioni
    assert len(df) == 2
    # Ticker normalizzati
    tickers = df["ticker"].tolist()
    assert "AAPL" in tickers
    assert "MSFT" in tickers
    # Direction normalizzate
    directions = df["direction"].tolist()
    assert "LONG" in directions  # da "Buy"
    assert "SHORT" in directions  # da "Sell"
    # Quantity numerica
    assert df["quantity"].iloc[0] in (10.0, 5.0)


def _make_xlsx_clean_header() -> bytes:
    """XLSX senza righe decorative, header gia' al posto giusto."""
    wb = Workbook()
    ws = wb.active
    ws.title = "Open Positions"
    ws.append(["Symbol", "Type", "Units", "Open Rate"])
    ws.append(["TSLA", "Buy", 3, 250.0])
    out = BytesIO()
    wb.save(out)
    out.seek(0)
    return out.getvalue()


def test_parse_xlsx_clean_header() -> None:
    """Sanity check: XLSX 'pulito' funziona senza riposizionamento."""
    parser = EToroParser()
    df = parser.parse(_make_xlsx_clean_header())
    assert len(df) == 1
    assert df["ticker"].iloc[0] == "TSLA"
    assert df["direction"].iloc[0] == "LONG"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
